### PR TITLE
Code cleanup

### PR DESCRIPTION
**Pull request by hershen**
Code cleanup following Michael's suggestions + some other cleanup I found along the way.

### CODE REVIEW

**Review by oorijsonar — APPROVED** [review]

**Comment by michaelJSonar** [comment]
hello! uri sent me here!

looks good! but there's still the `istream&` and `ostream&` reference fields in `Reader` 🙂 

i recommend using either a `std::reference_wrapper` or a pointer for this purpose

**Comment by hershen** [comment]
Thanks Michael for your thoughtful comments and for taking a look at the project!
After much fiddling, I managed to remove the reference qualifier from those variables. Of course, it's such a simple change, but it took me a few hours to find it. Let me know what you think of it now.

I completely agree with your concerns about reference member variables (and I think it's much better now without references). But I don't understand why your suggestion of using pointers or ```std::reference_wrapper```s is a better solution. To me it seems like it suffers from the same lifetime issues a reference member variable is prone to. Uri tried to explain it to me, without success. What am I missing?

**Comment by michaelJSonar** [comment]
i really like your solution! even better than what i was recommending 😆 

> To me it seems like it suffers from the same lifetime issues a reference member variable is prone to.

when i'm designing a class, my process is basically this for figuring out how to define the fields

1) can i copy it? if so, copy it (least dangerous, but can be slow, or not allowed for singleton objects)
2) if i can't copy it, can i safely use some kind of indirection? if yes, a pointer (or rarely a `reference_wrapper`).
3) if i can't safely keep a reference to it, it needs to be passed in to the methods that need it. i can't make it a field at all.

i went for (2) here because my gut feeling was "oh, you can't copy `std::cout`", but you found an API to do that 🙂 

one other option (which, again, would not work here due to needing to allow for `std::cout`) is to use a `std::shared_ptr`, which will extend an object's lifetime if necessary - but everybody needs to agree that this object is managed by the `std::shared_ptr`, or else you get lifetime issues like before. i don't like this option because it makes it hard to reason about lifetimes, but it does exist when you need it.

**Comment by oorijsonar** [comment]
Nit: It would have been better to have the new commit in a new PR, this one had already been approved and had a specific theme. I blame @michaelJSonar. Despite not being asked to review again, I approve https://github.com/hershen/hersh/pull/9/commits/d3e81b2efd28bc880e32301e3e3a93d36826469e.

**Comment by hershen** [comment]
> when i'm designing a class, my process is basically this for figuring out how to define the fields
> 
> 1. can i copy it? if so, copy it (least dangerous, but can be slow, or not allowed for singleton objects)
> 2. if i can't copy it, can i safely use some kind of indirection? if yes, a pointer (or rarely a `reference_wrapper`).
> 3. if i can't safely keep a reference to it, it needs to be passed in to the methods that need it. i can't make it a field at all.

Thank you for the explanation! I guess my question is why you prefer a pointer or `reference_wrapper` over a "raw" reference?

> i went for (2) here because my gut feeling was "oh, you can't copy `std::cout`", but you found an API to do that slightly_smiling_face

To be fair, it is true you can't copy an `std::cout` object. It's only its internal buffer that can be "hijacked".

**Comment by michaelJSonar** [comment]
> I guess my question is why you prefer a pointer or reference_wrapper over a "raw" reference?

so this preference actually has nothing to do with lifetimes (you are correct that all three alternatives have this problem, since they're all pointers underneath), and more to do with reference members being unwieldy in general. since all three approaches boil down to a pointer, why use the one that has caveats you need to remember? some examples:

* if you have a reference member, you have to define `operator=`, or else re-assignment won't compile (or on old compilers, _will_ compile but not do what you expect)
* if you try to rebind the reference, you can't; it will assign through (references can only be bound to a referent on initialization, whereas pointers and `reference_wrapper`s can be reseated without condition)
* a reference "looks like" a normal variable at usage sites, so if you have crashes or memory corruption due to lifetime issues, you might not notice right away that a reference field has the potential to be involved in the problem
* this can arguably be a pro or a con, but references cannot be null (although neither can `reference_wrapper`s)

**Comment by hershen** [comment]
Hmm, very enlightening, thank you. There's even a [C++ core guidelines guide](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rc-constref) for that.
I guess I always thought that references are superior to pointers because of your last point. But your other points are convincing.
Thanks, I learned a lot!

**Pull request merged**
